apiVersion: v1
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:Yk+3scJ5lkSvM5bW9FR0Xmo0BykwHbYminnQsopa+OapUDcFQA5FN8TZeLm7AA7n+ICZizaGMqNZm5Qrysg7YRF2W3rZjmc03mDlTsSwse5QBITNpe3El8KSLKFUHlnLaim1l5GDmjNcM3jGl5HQYm9hiTsCmVXZcCpvhxOK5NGWxyFTsR2oxcdxswoMkFDlQP+IQce68g+61wBTUoHq7wEvQU3ig26Olj1Qx6BAxTIo8iVCZW3g+C8xdlmMda0RNT0dQDisLKNdbKzY8yyEJ8mhOv4aAcIiBMkEsDXLuUh1aCwxj7TTdIiGJYBSvnc36HUw0zknortE0g8jSYywkjcNKyHTa/n9+rHXkB8MXN/CQdIO5Pp6MnLzdEsGxA2VP7r2M2ZeYg/n7u66H86ADbMgwp0up2IBWR7MOB/E2NJ3/tY+E42cloQ7Cm39HP6ZnR1wlKX0Mj3EBfaCLiTzVIz8RNKw0GnSvcu/kLPuSS5iRqb5Jl3tSrO0gdqtHYMNg/V+UeaDzT4m0fP/kIrOwistfpVZJN/Wv9lmbnLkQE6nHm1LsWw9KK7Yhca2lnrCJ9NoEZOKakeJczDP4xwvcVUngIXARWKusENRTWkMbkVxw0nWt4iKXJ2i79WA3cLlpASACr9dELEn+AmZ2UYq4M+1DssdYP/iOFzf+V+aCagXxsFVNP09f8NyuR/wFE0B1Rxq3d/uTLPjvYpBGszQY83+pi63wTqi/9ykTc17RmJ0WyWfKy5nhFYJNzQ65fD25rqCESDg3K6JRPUwo5Vf0IqBSgLyF4oYdTaNy/myDKG9Bl0DMoljfiWWVfBets/MsBcI0aNSNRvT8i05G/Xkttox7a6zbXoT28sJw+a3TWw6EF4S/OfwR/HxuMqt8K1Xamtz9C0nv5vsU5HReZgro2aDZhIPaJRywVjBN81IcS9QwwTjmys53pwaUfpbXcaWaLspG9NS7ilVKhWEGtKSl2xq4RFRVWAG9HKdZu2Ar6EZ5HM+Xf5jrsK/XTvw4KvHNsRfs/5hQCjSMsITsDW6Zx/Jlb10RK8kDplLNfuRcbBCULfYTyMLl2by9YRTuDmgtfYEwSAs6aZ8J7UOKNU4aZSppf6Vx6uqoCk708F0D3pAdvqvPz4/UG/TNITyQOD4H6KAZw6L1L2cBPgV5G9T0PBbwzMbd6Uic1EWk3w8USqoRNRLv6wLxPSDwUaW598p7ZMVirlljXjua3L3Mgw2lsbqqp3LkwLjUeA1iVngeF6K8Ccq8kHpmaNoD7iqsFSpcMACPIaM2DoI/LNNosbOt9BMNfHNW5GLuZZEtE1b4ZZSI3ZOdB1OpBgi6OzmKT2gPiGUImimPQz5V12GQ5ALucPp4jx7MUDPJxUy5M+QXP2OyKAEBxLrU21eHqFqDjQm7EquKBiHphYW9DlGSoS06b3zsLNAx4hexdvdB40ygRimX+zbkvzOPDVgmnxr02qeI8EA2lnTEdwcYpg5t9dPVPJRqJUWyMMbHCr6rF4GEhyHbOPo8HI/BzNH7/fhLH1cASqmTREV++rznKBWsHHtns1H8tERLvRscSl45znnJdJSoagbaT9gtNxO5kYz4XfbRXNW447PhsmS0I71DxI7oDQDJSfKti4hzh6VrbxspNZMHRwjJGJ0+dsO2+m+jWaKk185DOHDs19tyOnoP1SNAa1Gwj/hw5s3iB4ydHKNJ4+zmT/E3tNAwUjCtZz+OhXXVqEM3UorfVUE12IARXPscqIAlJS/d3roUxCc/aztGLDulvUhACRK/BCn4eDB/J8bJSWmJx15PxiIkwBB7xdBgqdT6iTlfZmM70g2FMnJmgJpLNQ59H1Pi6IC6aDebFMQLfXweGptxhi+imbEQLs/IfIGEkwMnjXdNiB3X0BcAxayQEgkmjphRFq6UNxeQ1VpvmscM60+OsC8gP/D4EYzfmt8D3diEEsPrKwtVDAOfCofyppF,iv:vB8tJeR3dsEEA7kchDkG1Qq7ioUaWqWj/llAauJzovE=,tag:ve/DLURDTlPEn2H9XPpNdA==,type:str]
        server: https://10.14.10.30:6443
      name: draven.cluster
contexts:
    - context:
        cluster: draven.cluster
        namespace: fairagro-advanced-middleware
        user: fairagro-m42-admin
      name: draven_fairagro-advanced-middleware
    - context:
        cluster: draven.cluster
        namespace: fairagro-advanced-middleware-harvester
        user: fairagro-m42-admin
      name: draven_fairagro-advanced-middleware-harvester
    - context:
        cluster: draven.cluster
        namespace: fairagro-advanced-middleware-sql-to-arc
        user: fairagro-m42-admin
      name: draven_fairagro-advanced-middleware-sql-to-arc
    - context:
        cluster: draven.cluster
        namespace: fairagro-basic-middleware
        user: fairagro-m42-admin
      name: draven_fairagro-basic-middleware
    - context:
        cluster: draven.cluster
        namespace: fairagro-m42-applications
        user: fairagro-m42-admin
      name: draven_fairagro-m42-applications
current-context: draven_fairagro-m42-applications
kind: Config
users:
    - name: fairagro-m42-admin
      user:
        client-certificate-data: ENC[AES256_GCM,data:pDjiYYH4h7OTVdplWNbybmgs55SHTdLXt1rdnJc41t3HzF7ZXymoHmpxiUYy6H2rH5K98b6PFmeKj9dKfA01dw+RhKAXod7Si+C1aIsJ/BhpjNVzQXUW4UvUpFBdwJqBY89S+kd4eLT6TCpYQnn0K8pI4pGvHJc+9/KqsewNK0fjfA7ERZSWcIA4KKmMXJs4pVjWzI0r/ll6Eg3kdRrNHPD+xdvOwvirfT5lQWWCVgocBvQDOOQpR5eRf7pB1m7jyvl5S2fmQdruZ7AjxDIErgGeDJ4dM53gIbFCelZpDsb5KuLhpuYQOJ17aAMh4F/OXRRtJPK3UZEK/6x8QbQitZBd14gKyR+qC4cQs+hziFzU3r04W7yHei00+Jm2AwQdV9hANMWaetffB28fNPuZ9PYIdZt98mlOZyotKVO61uZkUgwBsC7r1LN7t91XhxZHTmQbkzKhgEKRm6kru+Oxf4y2Ybd5+I8TpOW+GTZz6TEgxb2LaEkwTk/fdpRUpKufNnbUQ7edBEfZPh3J3ZWwR224qVydWIWqna/brV7D9N/TmtiMELJ9332K0jKIExjo1uONFFFd+oWW9dTcElHUrsiN+kEd6nSriaU4vvJUBoCmdxAwj+Za/Obx9KunlCXR6CVLX34Ddlc0rzVKkfZE7ScjNjX8JU31ghfFEFlOClutcY5onJTMlYJJ6/u1BgnktlTwq387PZapJ8twSIlm2+YcSw9XOMcN64mAZOITqChFIGekxtilSYCpqeUIOFthrSvJC6p2PW3TtoSLlxUyg/GRBhpKpugFv1qqU71meV7nkvJRejUTgAOEgj2BOLFv005hElv8B3IN3tK2afC7soZJpOMJqBONCvB7iZglFtxzZbQ37GYDk6gx7O5JkBkiVTVQ9mOQPFqP+dMWRPshkzkTcyYHoVIrH78zXppgymIcpNlKVf2VeW/yoz+DinlfhAyrwiDMFHwJLLun3W3e1kjsOmx9PsrlZjM2DJAHcV2yrN8/5Gs/d+eNLKgvTl4PNCbpiPl6ohuwBx021UgJuQoF4RlXTJJrkcJEFbOCClojTMVsxWSerwB8jUqegnI147kP/cSTNdhWwdlBVNwUR6kaTuKM0+QNN6OlOL8ykY3dd+Tm4DvDZZGfegL6FUXhHeIxT9sBdMf1CI/2tHLuCVD85FcSmEaG5GBMkY3tzPMbeOYimsW4q6coehvhIBzailPY6IRSe5b/ntbjjGuJT5rziAwt9aA60oKX78o/R7GbfuzPIhgDIbOrJ+w5EKaXuOQXlROqHqcFHdJv8z8ljAoM1tE8xkQzggzKzj4U6HHrITWIaoITJnPsyeztw+SO1mpQzhbKVjQAMVSXyBBX8qnfNdFx1MxmVHdjWwl2M8ReDpKMDpvlRw==,iv:RUSHbR0fowCwolLX6ZmjGpy3VYOvMOgqiq+rVnG5RCw=,tag:YqQt73yEGBECWHcpD+GBDA==,type:str]
        client-key-data: ENC[AES256_GCM,data:uUTfDgdk+rIb2Ald9CVj300ihcgeS3P8DUH/XcXAgZvPrPx5PyWrDWqTH7Wx5Mh6eEQMKyXkNJn0PzZAuHnCh4PkZu6LXPrrjS6NJ1mMwxJmukZ5eQmQlw+QB3LbcieNxM/+wWqXhlBOrWkPEQMJVzkm+OpkjwXrE+eI6WOfaqclvPQaJB0I2r12v3XP1ytIOjCcIXKAoX7rbsHwtmbldQ==,iv:IJJwj6yIazLTkBrmISLYirmX7ZPeLeZpGV8y5qU1R8w=,tag:mE9+2j3fUmji1UJKGPMWaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQWVONEFBZEJkMWRkQ3F6
            d2hTSlpHQjYzbzJNaCtlYVdrUzYzc1B6V0ZFCkgxVy9FR1IvKzJXbkNmTzNzQ1Fm
            dWNVL2pWUWIzblEyNE9BdEEzaVpIS2cKLS0tIGZqMWgvNlA3UzhuRE5ZS3ozZktC
            T1djTkd2QytNS1VaNUdkSW9sY3lxSU0K64je/cZUCdmhsYKKBulVUBJ9bhz4R4cz
            vSVI454UO5i9Xe1xzdII1kSb4knkcmghrsggaiRXj4o8ykc/YhZYkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1442vmk8fl5nxrejuj0g6a63cqdw7q7ufvnxuqf3wcsnetgmv2phsl8eufu
    encrypted_regex: -data
    lastmodified: "2026-08-18T15:33:18Z"
    mac: ENC[AES256_GCM,data:zWvTptCwhbtJQX8cP2ZA/uM2WQdImj+S8sNkp/jBNhU7tHgtgJ/f2KPdvGsWnkcYnkdpjjIN05G1CYlWaBZ+FWIPBc2Hmr85w3oa27CbE+EiPe9nMrAGfp646JJOiOky6N1J3Ki3WaVzdS+Sr0WGyxsJv7r4Wny7F/LrVEL7+IE=,iv:vHmQBlI85fz15DRRUgUYHMy5JM7WACWuBd02QyaQF2Q=,tag:OopQx0IYslc/vpte/Mn/jw==,type:str]
    pgp:
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3FtoE4fF3lxAQ/7B7fIyly/6SLRb+nhv0lXECYlsgAIHYJUUDpVX7/K4U/5
            fPuSOB2XtrDb2TvXLMePEig+Xo1IRKauYZSfuz5/lprFuxi46nHAGBhPd59CLTQP
            WuIgOs4ovSGU0kM3hg8+bhif+aklE0AgxZZJggR8fzpieLyucB3hQaF2L/lE+T6T
            pPAm49Z01X/4l624Yy6E7E0BatXu19TWuLQaohhbxGWhuNv83rSEikkzDH19Ryxl
            uddfC9YcB/ekC533ouX+VOBcIJ3cFMihtfYjbPRxG8bc4JaJby4S6oaxir6u6gio
            q5jOrvXAH+e8NqLiGJk+CGu1vUv7Jqn6j564Z+xRrMAypVToogd/392uYl8IQowZ
            pCM7SEC7Kgqfm/9mMU2g1sbsRf4PH9GLWhVShV5gLUnJLxsBwtnr6CPIckpdWmO9
            GlRa/TXjmBNH1PHGsKQx48Vv5QfKqq6xAKxxSDneSRa3WDopDylwCM+/MSPy4ena
            HQrnSGbgRtCPO9SZgwgl8wssYT+oTiB4LHD7Faj8XlvkYUgFmilKEtYZDIaz1o6i
            pL2I7F6xxJlf1T23uTxFc4vjKSk6Duz8QIVGFvo6JbEoaQ5cQYxUz2dUV5uC8Gtc
            1d5r0O3K1Ww//9uazBr3FJaaRpB01YhmipGNISs9JstgATl7vjAs3hfEqf8pIKDS
            XgFs7xZusyUOFI7CJgtFpKmsTc0eT6nMjNCx5CTng28mRDQExBqPxQxHXkue+IBJ
            obYLXNMFut+54ZJ1eaQIwRzrl+aNq6XPhERxWOttEDs0ds7RHS6Nv+nKJYpjK20=
            =fCCt
            -----END PGP MESSAGE-----
          fp: DC8231FEA934DB14D402E72D3B6555ADB3910EAE
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0NuJZWRmFubAQ/+PeMEhjE0bcc3JYO+2z0lvoSw6jwGaS4+NgwWimRRqI8x
            3LzIp7mGofiRcaI98hjVsuZ2vXhyrblB5uC07azUu7THvFsnIXMqN6e6T1rV9m25
            egm6WnEbr39ctnlNHF2AMtycKCUHWAM5Wo0hlj0WfRhFHlHLz62/RenX4xY6Z6Ym
            D/hCwMu9Y8JacX0zQKbTiri/S8cxCPHJsYJx3Hq1iCotcHvVw2ypdW6OVf7TgBIn
            vAlgbfpEx7uGbQMqejZRhRw4TK+IpsZw8tO7NcLGpRmJqPONHpgJmniA5qQtK8NP
            CPww2pessni377RrAQP0kHFaKjkenJq6cK0mne8CazoTQJmgi9UiMjvy+OLi3CwQ
            V5W2C2dkkmFKa9pGe2yzMe19Z8pey/VuL7C42VSK57X9zcSduASMPWaX3bGec8Yp
            BhKI431IOV7U1Q0WIxrWQUWfQ9TVie+qgPg5NQOHac4Zhni9y+o7hz3ijZkhTJi/
            v3+UycnG4Ccvj5M5lQxoQhlTAxsOYSZsxm7EiBwkLLpvgvg9wFm019bmReSoE60J
            RN87Ff99xBkKC7mM5JxjBP1c1uRaZB7wFc0cvjmqF2blFAAGvXyT2qyCWGylqTct
            t6sAIf+1Zslrk4fpIDLZhiOKAzSnXayurxNmP8CsicCaqg/vRhtj/nSBSsOtJfDS
            XgHbmPEGRushltKka4L03ZmRhfZ61+YaWDgd6O/cKUzMLsbAP4XFQA16jk3ObioE
            PIjYhFMA5jWwR29PthpLmyYrdDBZHHh5zeqVqtNXYQ9cfFbUouTdEEppW40WKrU=
            =SdcG
            -----END PGP MESSAGE-----
          fp: 4CA6C33F1261AC9FFE27679791A3FC54A5E4B97E
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5jdJleHfCY0SAQdAuyeJxP4rcmO4W1JpjakxHXfpeqbmjQTqgJrr/cmM7jEw
            FTiy8Prooxgx1VDsrD1B9Jc9MW13V4CjbR4MhwtZwVi3aQCFTF1f7UWsoaahAI9v
            0l4BUsCxQuxpKLledw4mZAuKUGEYB+/0lhpGkozo2NrJSzVWmRerahc5yMzZyK0w
            xjysZVK1WfiTtOFIkJqSz2iIkpgOqtdMxC0MMpMMtPH5dGPR9ZPBVPmoGZ5/X6nu
            =j5H2
            -----END PGP MESSAGE-----
          fp: CC7B10CE8D78010ABB043F8DB1C462E90012ECFE
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DQRb8ubOX6YsSAQdAwoUw6OreP+HLkdoinjdweBDMdjQdej68bHPpRU3tCD0w
            fF1O5eo/klVMycZSXndAdQEMgkhR/QBqqJP9EDbyB2LoOxzzXSN+H0HbabTFhP/n
            0l4Bf9sQWQPvJWxwbO9fgkRWd/i8LzN/vo2PMRU2ggeP6Qd8sOA0doFz0twxM4gK
            bxMDfyQzwL2/kp20viYpyLe8ijyPt6I+RXsr8+Pql6Oq/l2O2gCAlHL5gALsWf25
            =B5tP
            -----END PGP MESSAGE-----
          fp: FB3F2A3A200A09F4DD29A381C0946395407792FB
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA7X1abf8MUKHAQv/b6bgugexhMlvNsWjFnmUGr8FOCdM20J09Nva5JZsrC+9
            mRHfX6gLBrAAYQfooPrY4EFdvSDdASX6werYCOaVGc1Y0/rEPNuznfLtSuLp/jpJ
            eUlZGWWwYOc8dr4ylYZHAAQD3qg7sQtmz8huN7X4MNsO2zTXIYdPo/Dc/yk2WYVk
            E/uUfxAPsQPQgI19Z78kbUQkjvmaikqELqBBU6Bkrp9aLgX1IPp+xngpF/a7GoCu
            jLMLVoTDKRC13vG0MjGKXulSifWJUIgC2tfF8QNxUIJn0vlyHGlKRyu/AjK/PZqP
            qSXUMBrrxf4WriGJVy8blmi5uXzUJXoqJHNlo7GVlISby+iU3KtERV4f/pvlknIU
            SQNEoNr629wMWXi9n/EOu89FLR5xulzYBsGGwAd30t0ty4UVzlyC6e/0UHCedcfT
            mpqMV12SAS+Y9Nb+Jni7EJn6HOeK49H4hHay1e8Ia7CmBJL4VB8tR8CVykzouR89
            Kh7fwDaMPZZ5YSs98RWw0l4BnC/nsoyQNhmPNPs8ZZkqGo/U6KwdIVU5YQJ2iz0U
            /KVY213wW00vB1N2YfCDShva802xiBXYJFno6HW24BQ2ycKwR013y0ufkFW37s83
            YV2eLftyIaDYe/acQwat
            =Mw1x
            -----END PGP MESSAGE-----
          fp: C1FE6C5499EFD997370B81346B3FBEE862549442
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAx7vFZ2Rppb0AQ/7BDp74f//1IQ63hiqXdAtz5or856qgH6aN06X5+1php6+
            6E5dNyuabJMGcr3vpQVdJMHS31x54kmM/MFDfn9xPsVUCrIqZArLOzyNyjvoKZ32
            OKKc3WwGyMGRGobA53QIY+Q9LMXEjTfyNvdf5u2NFreWelmrFDa5/zUWBSyrukIZ
            ZPog6/QZB8VCLqdS4NxNlRUowCYkYOQdYE3Bu3HrxOd6rGJTCTYzx1fdoBntnN8k
            VgX/4FF+X9bVFhkIIVPgLPX93qetyJjV4OKVNor1ZL2WrmCHX8vUIbn1oMtxodko
            w8jicloYu8nd34yjJzAkOAgb7hgi9iRkFA3qrTHf+uenDQTVM6iHhdMMIHeqSvq4
            RnDA4PGV3aeBhI4ZQSOvvxRUxu679+CL5PR18NMwUmfmF/wAApQp7TyPDkBc+Krd
            9NA9wqc4R6ZPcXGWsuQgEjtmMvtMdqXmw33z1t721Z77l9f5zYqifFO/OsTbaFVe
            is0n9j431h4HYDQix5Y9p1NbKQCMDnm7/55v0pLvD7vXK/6t5jz9QJV+t8eRDLxB
            /ev/EM3TH8kOWAs2ApezGsUi1TQSe1XhFj2EzFXPTsZPozqCgLBc19hrvHbJO7In
            /ezNYI2geCZXDClgBiSJ+HMmZXL/P/mLCDAt5ZrUgL0ojx4xataLOVHUL9pZQzfS
            XgG8p2Ri+5YHZjL94iA4KjikhcmIWMPbUGHwA7FHYqjZPUy3Pvhr18VrSNGlb6Bb
            8U+pKwvuXbPkX/2CgOKRgGsj1b4QwkvrCihdxkQckjlyvZ9dPfVfd9VN3UxC+DE=
            =Fl9h
            -----END PGP MESSAGE-----
          fp: 1AF3192AB6B7B0CE2167281CFB2B72AC45F17D3A
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjxsgKazaEGsSAQdAKX9JgjXwkbrN9p2kp1TZVFFc9mSNCK7HVd3pMzYbyzkw
            KUzn7esPTyfO7I40VEH7TYgiixqwKcJGAQnxRxt2oaZ2xvXiHtdfTtCBmZK47JCE
            0l4BdlV09FYCVS8/2DPeeO3ryelwBA329E2T9InsEy4tkR2MGgPFJyIqCvahqbT7
            FAR3yWMNtWSod9vFFUPRD+XHRVk1G/+7wppxWz7TGIHjMTinmIXXmwx2gMp24dtK
            =LWIa
            -----END PGP MESSAGE-----
          fp: 97BAD070076E18F23DE40CF367FBD7D6A827909E
        - created_at: "2026-08-18T15:33:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8hhMuYteRVoSAQdAfS2tFJRaekXQapbQg4L9S+MWs5F9mhaQ29KhQCH7XVIw
            7Skh+OkH/IVc87/V2TpMcdrmiq7EpJUdfwTyJCVHk446FdFJsMqiPUxcYhRLed6D
            0l4BQRuzQdj9EqnrbZYf7NjPHqCXRSoxBc3PVcHWEZsyPvPCNVGcseQ/INNU3hk0
            Wd2NMk20OeIENQAYK12b7IfLl1ZXaYTyOOgS/hX6/BPBZ1b1QfH6nlpeUslWybuC
            =/Usl
            -----END PGP MESSAGE-----
          fp: 26A3171FCB66E2E447AE859A2B06F9427738845B
    version: 3.13.1
