apiVersion: ENC[AES256_GCM,data:C8w=,iv:Rs4tbCjHb2QODWXoch4jQHqCt5lx/iuobcBbAB08134=,tag:3N6pAOKhdRJF6Hf6ZhDIgQ==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:wVYHQB4sPrQcE3Apja3iJZUvS4Es58BS9Dkkv9i5Nuruy6J4GsUICgow24uu1RX7FGy50KeS+aZpEPggu9uOFhUmfUwyXfIaEq0OQHenmqDg4+GgT2wdo1e0m0PBXmhEXZ6lFdh2REyTk1hsKkZVqHPDt5AFP8VIZqtcghK6e0a0PWV5BAKeygY0l3Thm+5qR7ToJCl+kWBSVCabf7smglw4mARX+/o9Ro1vFOSRnLT3c3cOWAPx8kBUwbqY7znRAwgYBAIA4hdrtEq3rV0+3Nozfb1sbz+GhIT+aCDOL1nvEV5JRforn3O54GeGBgp4J4JrIwhM34bXv8i1MfsMCqa3OFzQ+Iub/TZFBEXEugY3MeKYQCcCaMQqhFkiQ4MgRuH08dzpkW8LuVs6itAnKLkc+rVfDcmXQf1hVSJ6be0Cdat/Fl4i1ZJJsMQfdhNLiGJ6dPZeQ6uCk3INfL1ES07/1fHxhLKhxFm+RSzWMG/Ur9Z92+isEsuEtyoMepmu9at1s9vZNMd3RwP5w4M5v/C7LrRvoDqwkWmdeJcjQ07muZL3lX99Sd0tSsGVaK8WkQy/eGbUQN21BlOnVPZFlYxXWPS/wZRr6+Loc2DAToaQua8Z993LbHqjqMRhNL+Lq01AHVmvmzGsaA8M4XbMBjyz4D0KIV+oMYqOLfLiX0WT7Thxwgf6O886sGWvpoyOplRMRKR6w25vvQ52eaxMWCeZPFGCMZY0edQlE3wEYVzDMRyphNOLxtIsYJiBG5dVnT8lsqsm8lCyKhvQEquPlFnAh2lVRq4t/Valpz4M/RfqEhdjU+jg+DhcwvFtfV4uTBPhdKvqZ7k/kcH+7+CO2OrnE2VpdzU39OG9cIvdxZa/Qorkn1BIdM+jbRIm1EeAo4W9FdNylF+GqrUuBt4WEUMYxjVR2WKt950iMf06zx6UaKDCvmpDtaXmtvbMCBtgoliQnCCLQzbfJ9rzLm5n03/0eb301jP5XQWq06e9Qpr9rrxnqaDsCqzbLVyfNKI01gdDMmKNkU6bguHHrQimMFr6a4GlN1FwtCJoxNdHWONYCSjxUXzfcl1eYKuHgDNw1YnXrCPjHiz0ZguyQvf5ZDQZl+g4Fes2vymLsY0CHwOoFfee/8PzCq4QYw+rtcFcSfP2BlvysLeyDGC2+cKC0d/Kgt92xflS+qm3DXymBEiGHy6Cva2PsPyNwcGVkOnM+70/0v+DeSkUV+iKxz9H1X2pMwQ9I49ogPxMCCbtUji29rIhAL2K+HY0nmkOgRSBT9sPwI7ko6+ZKjLE2c+xdabBRkeePJrC+5FUGvoIM0tQdKYsoZP66XjZlJIu9os7X/Krvrmes2NpX8PUqGMibTi+DSgtmfm50aQxyonkU5uECE/cGI7Tu9yvJt/0hi0GtJpyp3ff24Yo2qHsBBoDtC/8nWtglc6gcGmCEXczAoClP7QWQKSbC9nKBJOWDBTfBkI+lGxvOMohvsQZbZSNn6XPvlf7DWneeKWsVI9b5bFe+2WW/496tKboSjyMSm/hEoygRSBSabkMwhlGFlv18/7V6/UwF4MP1ZuTauGWbj1ZbHfhsceunALj/1N4ToXV+mt7W+2cxxrzUMjlae+pMMwkTaTuYnWrmsGUJlG/tgR1xRHeV2yakEmbdb6STAPmUAtaXQl6cB1qsVYRaFufgpUBio9kItctXRKVc2J/zthNAMxoUwkK0TrVPsW/TteWU3gpKBCsMyKh7ztsd67uAYhCBZL3VzmzoiGw0VGscCmN4189qyVGYP3R4MFt/MFwB7w7cMAIIHDQiJuXadfKmixAo1f9NCcYsj4eNvcKdRHFeQdeslGaAblTd+btz15f7ZTiZuLoeltG99OmcJq2cY2IW3ceuxAkyOHbLzSInYTnCGKkeq9ppNBYmDFZa/agz+BIg88xPgkAMxPNXeU9T3eYL8rVwLXwbUvlNGXiKMdhSNS5,iv:xFnIb6zQ31dM+hKF8PAJGla6LwbfvPttlUGuBbHsZ5Y=,tag:bPK70aQdtN56WqjJbaH0QA==,type:str]
        server: ENC[AES256_GCM,data:WfxtMwWugx0dxcbbjcFip1fWqWYLHnGr,iv:3h8EMTswS1UCikYnLDV4W3dxYN5eGj7Vdk9I2vPcNyo=,tag:sFBr2u7s3Ww+IKFQJnFVrw==,type:str]
      name: ENC[AES256_GCM,data:PVMLaDDjxT1V6VJv+mI=,iv:6AwGAr8/XUow7m74wVD/v7LGtsqJB6gCUjAX5mbZaKs=,tag:Kpl55mDNRNydhoHc6MNVLA==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:73lXGKXlKLazi79bGS4=,iv:dJ7bWWq1yM64my3QOFpUQuYT36OB+6v94OnXE/7J5jk=,tag:xpoLYSqHBGHxHE8O/2pQyA==,type:str]
        namespace: ENC[AES256_GCM,data:MpvcbKiNIpX8XhLZIhAWyWaSGNNXL6Ef/w==,iv:zFwp0/2fMerR2h4AlVSAum7bzNAN3/PaR5+Q1+MLQrg=,tag:/dKzl9srCM/IZI8RwDYOUg==,type:str]
        user: ENC[AES256_GCM,data:Ce4nhkr/nlalVvqBWhScRwq4,iv:2xIEhRCDBmWDvx7E5KTey5xRhCXhytvdXyZ2ZfogoGc=,tag:tXMyXOV9c4nhvFZ4E1ZSbg==,type:str]
      name: ENC[AES256_GCM,data:8aDT9LBhSyig6Mf2aCAWXGJW5Gy4FctRcY+SBKYDL2k=,iv:+XtB7ufvcQ9SczmGYYtaPO0M7ajc8geLsT/WsHcG024=,tag:5mo0pv4flNI03veOiiaokA==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:HRJHoDa4oajvcLR95Ho=,iv:H4b9P/vjcnlHUdfJCUflJbSQs81dHF0DvJDK1vhqw0Q=,tag:QVZBr+34LRQhmNmg4GM9Vw==,type:str]
        namespace: ENC[AES256_GCM,data:Hg2fzpWTFttGn2psTuU0SJVleaM8Xef6xQ==,iv:YpaTBBWrNHFXMKXH1SyOxY+lKQFFnAS5DRFwCyHF5Lc=,tag:xvh4K8IZYHLtXzQbsycopQ==,type:str]
        user: ENC[AES256_GCM,data:kuTaloAm/JV0qvWwPG7Fr8sE,iv:cjHlOHveOcIO0vfJJcCsZIMMlqpCEoI3gBNLgwVBNNI=,tag:f1KdtgthDBXC0reN7ChFQQ==,type:str]
      name: ENC[AES256_GCM,data:cFG5z36Buxg3NWbQ1whhLEfnTHZHgvlKdwO6aiPHR+k=,iv:tJDsPIcViajxnm+isxo4NbI+XIMR+kj9jCivGCwse4g=,tag:kJozdjqyBSQfLlPSHPSY8w==,type:str]
current-context: ENC[AES256_GCM,data:g1RCTTcgT4QVepYByzTeYfKYHgdKKBAW0CEVe0YdShU=,iv:YwDY40XVXwXKTMrUPsVDW7ncnQguVCvYqtmPL/IsEr0=,tag:wUBHzCWmil3ShpfQx6z3RA==,type:str]
kind: ENC[AES256_GCM,data:iUXZnTFl,iv:iZjx5GY59O/0etFxthpoYY0oXgpf+YWd3oSCe/ttzNg=,tag:QGLSqYBSHTM+0xHlCZ7owA==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:OrrDU3SYdqnUwK9GHT6GhiOM,iv:ZY4o+J5fWO5byJJeZfkEnrvY5JKrUwBjsYQxhQKpS1c=,tag:A3hFpnDm/Z2jv6oT+LisdQ==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:jDRvmvzdL65Ob6cMg5RNJLJBAqDeT5hv7sxnMWxq6BPTcG4oLgjT/Dv28/wImm/xT+dUCNmEndBraX7yYL0FpmXiSFNZovVsT28HKUxXdC7z086XLyxS6MzQaYbGC02/yefrCr2SAu3vEhs0grZJy7hapmqNgXVKzWkEYXgMl19Df3OEaJH/vuVSxWQLgU2WKhZ3EIk+Bhm0w6hnci5EHmm3MoRwZTYd+ARme480YGDnWsD+s9WldPdotWrjRM7osnijhNxhLLwf8U9kVb3KhsgOKbjtDDtwHDULKrACGt8TTG6n9C91uhe7ULQ675ER2T+EpCWsobO71KceYTFj61JtGpFYNrBXrSpBNgGGzdMfcMZgtCUqhn6Hx2l9nuP1Y6Ygyhm8pbCPahgd7pT2yTDj4LN1ArNdHCfKmNdsfMwY0cwOT5Whzz7RA9x5hLRzfPY/G830qgDZ3hq5Jj6K3XgW022dmPUyh7LyWmieO7jAQWHgeqBVmn2U14F/feUebVW1EM2p/c7XPXWZPM6I1i3pSpqDaNUQRvuBDJzA/kTog7Sgcf+I7UWWvc7tTbzT+7bwk9sqsp1yZ1X19Tc1Qt6vK1VF9ZTTseNBtopAJDZm7DjEZ5BNCUPzZdH8rlOkyiNkSlnMoKhIVSxXg+t2VPjhz31Y/BeD07sa+B3TkdZKm/XNsklpygSsg8Pg9Ui155MJ/wloBUefJhQDSCKHmpONp+Q16TDOnAXXsQf0T4s8FLmGk97RhKEwI7GpNBcVUpmFdU5sSzpdvzYCTB3k8Bk3M2nixOt3kZpRDQD9LQ+ozLAAD/EqfEBx4aJMNAmGaROGUpuo+Gt4v/hZ20Ta540v9OkC3uS7f08vLPXewOqc2DQX+XI2RiMvNxB4+YoaT/sgOrOvYx8j+fZSI6SSAX+nt2qjto1FjAIjkSDdc6/u3AtdzKAEGZcWlyexhaO6Wr8xLuHgJJEzuJrgcK4k8ABIM2SLvny/VHzXAgaHL7lBG7Pa7+2bANNPcbzLesZwaa0cdLI27EYe+YDdS0t/84kvfWtJWfBpeyGGXGQcEbZwaG2MLgcPpOoKK/wXSNtXqKAwcj32p5sWCDy+RRMjOBgjlnd85u38B1sEIFz5PXro0sPXyL5m9tUMBYbu4xXF12n4+q5TxINkwEjOynnw7R0axngb5DdnV006bvZ9w2Xdc673euOiKIVT00gKLXpkNpdRmJVgh3lAd3i88aPehG8PZ/bfkfwyK2sG7oI7DeQjDQ+Dx0Cj5hiB8T6S+ngwfto1fbm62pOorMvFCVWMJr4PmXLtUNxrbFB3qoGPlAkksYRiBCVpHc9F5C5KFK4HN5zLvfkCgFi0lqsQ8nMiBQTMbCuyl6h4JbxfvlrrpMJDkHNlIBp6Bw==,iv:k3DV+9Iw/TOpRmtPj4XpZ4ThG4viZXwjuPl2QS/qhQw=,tag:dl/Jy+yPR2e/4Ym6s805gw==,type:str]
        client-key-data: ENC[AES256_GCM,data:Ysh1A/19GoRWIIWk9smW/AiZFLMq8ytlq0oP6JoGfAdrTgOXqXcK02FZ1qSRV5edoIgC7Tap1tQfPR7LzoiG5dLldBCrx1QPsV7GRptL6eUzY3UtwSFCfz+dltxqd1oe5niWo3synjYZpe6S13lS6Eiwu6YtURGEfkjUgFg4JOiqD3nimJ7kyi6oCWhnVeaVFIN+R2J8izJ1eZIhNlR3sA==,iv:2OARLZRwbCBKce7EKAOfUB6mmQQkHDMLj01sHwFiTbM=,tag:xOkcMpjXIKEdEgeGRyhxdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442vmk8fl5nxrejuj0g6a63cqdw7q7ufvnxuqf3wcsnetgmv2phsl8eufu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva0d4Z3dPTFlQdEZsazhT
            N2hobGx1cFFVMEJFYWxuSmtWUllXMVVTa1ZNCmlPb3g4a240M1VJM0NlTWpUQW0x
            RElOZGNJdVZUTE96ZmlsamY3VFZVcGsKLS0tIHFscFVXSkVxVitvWjBVSmNqanlN
            elcweFh2Zm9Xc09PRVlpVWZJdHFHTjAKJ8AXtMvGFe8g2Cy1PXvVQCNpgahztBMx
            qjd9QPC1N/hlzuc6sYx2ws1Z6Ca6ho8oWJ5NAyB3SIg9CTAnATKBpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-27T14:37:15Z"
    mac: ENC[AES256_GCM,data:GkDqCJ6bIyw5+wWZxZUkxfojXbp7CWp81HTSxQKpLyEibXvE/JkX8jxsRpeKNo4RhEBWgU2cSxfTuDDv/+lbEyPTB+XoQ9/EhczJom90z07UVXX1kfTqwBk+QxTK9FNkPBaJDj7SxnznwK51hZ2/G+h4/V7OgghYwMcUk2Q9KWg=,iv:enGy6R0JqGGoftITcr24RsEwBpq+ZKIF1/6HYQT9hF4=,tag:BMBVCFkosLUV/Qt7AVDXEQ==,type:str]
    pgp:
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3FtoE4fF3lxARAAq1qh8PiyISH24HaFlFN1maWUeQ90W3G1LPTIl0oNSROb
            W8cGPrGX971YfZHyoPP0ivA5+TVSzlLiYCKSvvdxngQuoOLQe6S1uihcCjj6ZQrW
            3e+EYxoVEht1TAf09AxIuv/uxn6CZ4dte5tRXKMq5qt8xwDY6nRmr3nmQcnvQXo/
            c0rHYb8AgwakS6bE48vft9m5whd2fOm8Dg4y/iaMxujflkCD5UMTfJOqKMeLt7ur
            fggyrwOXwlCbRRJbfWySHvL/mlXyivbuobZ0+pYdxJDvDP8s3XWX44Cq8vVJfjwa
            zednzJoTh/6KHM1jCAFPCBtMKMHz2nCQH3ELPPZk3dFXd3mZSfRac8DU4Wet4owf
            JpjPB88IVvXF8T4xa34PAgfg3MEOROmsWSxgbDWC/UOayg9ZSblfaY12C5APPYtQ
            BcFx6cQWnihJJHmgs/OAp1TRyrg+x1xxqzhcYyZA/miNpzyy8no4B1TU+06nwLJ0
            YiRqItfOXRCsjqcjX0fqzl0/uq1H+SsjwN/ctWSjWsl5ZykSmGMagPEM8we+82r7
            sJpj+oZepnE4/8wjwl1rupQn00NGUz68OomG3AcHG5oyUlJjwO8RlE6q4ezJOmEb
            OOgniyLRYjLnl2uG4WG4JRtGNCxsEBjM7u5A9/QZcYvFWZFHqk9CFIUMDCkkSmrS
            XgGk7G0gFJXwv7ryG+6bOy06loF1NNNK8qEIFdZhzeu0WAngis++syTZ3kJDoe7x
            60oLlmEvyw4y6dJ6i4xlTVloUrdMYp4jCZuvjecmzCz/ZCjLah2ZwIIK9iIjXo8=
            =DYGe
            -----END PGP MESSAGE-----
          fp: DC8231FEA934DB14D402E72D3B6555ADB3910EAE
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0NuJZWRmFubAQ/+NRgkQb7af2Ik9p38fRHrGkndGADDOrRKOu2zTn8CiHIK
            dO/a9C+kAIVtkCuGjs4EPxDIniZtrRq1RJvcNqZtq1vS08zVw6K1u2KbEVNJjY7Q
            OKRJii6j2Pi/6gl0/AFkssdCLoVCR/UAw8Tz3wIEHfQt7MmPdH+7uWl1CEL7r6zJ
            0JDIA28vgjNO/PvtcpLpSa14NmKXVTKptaeaEczO3s38rD50yipXSi6U3rLYE49r
            x4OFs9rMCcLgrliWhA/oEIznvTmWwMzVlWfiGxgUOWoh15rHOMkmLfMquK6Bzz+h
            nG+pfqR1RcjiySsYCuDx8fOu2pi7bYbBqy+hyAPK/4snRVWq+bujEJs86ken1pJZ
            nTFe3Xg/xALr55bOHImtxXGtGwyLKN9tOsnGDUY95N2MYjVkMmo5Ftn7r5rUklQb
            EamCTE8AU73TcPsbJ48tJVhnEAyjGSnbyYHNlBp84gDB4QhGoXyWBwfPQACTtVvf
            j/haqSWaH8egFNXhzQ4rmTT4zfpVmAY8jaQRsTDh9K1GOlTxLJMAXMpO5jW8wWDM
            plsWozgUwrOm/ck27oNUNo0itiQr/qJG5kw5/fP4XROhXavATKW41dUmdehyu2GR
            d1WI4/X65erivU2NrATTwpLeyaoWpAGT356lipebgx/3tPSJg1jGDtIo6xcLR9rS
            XgEm4Un87j1qIarxcJT9XUAC+WvhpLAkAkmJi326uEWKoVSbk9K2FJVb+INsfWA4
            rmmI6qve9CWEZdAqOgrDGfRbgPj3ppKeQIyXkHkcFunA4c5UTnUrTYaZMF7rNVs=
            =8VFN
            -----END PGP MESSAGE-----
          fp: 4CA6C33F1261AC9FFE27679791A3FC54A5E4B97E
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5jdJleHfCY0SAQdABQSAnCFDECOWk7ZOHFkqQBBi59A4JQuBQqfqzxrH3gsw
            gC80Amcnna52JYRJPmIpK75qXLHQtZXU2U4NvpLlrZFDjSKm2/IOk6qFQgY0Fgjt
            0l4BtU2OcHoT45QHuWmcwV26xrARtS8dKO51juoCEmtrDl0h4xc7XozlbG2dxIgV
            QQzDjbB+G2kJKQM9h+7xv2Unm734AnO3W+uxjjI3ymK5ZWCwhEaMiWpXt074wdgg
            =dYCf
            -----END PGP MESSAGE-----
          fp: CC7B10CE8D78010ABB043F8DB1C462E90012ECFE
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DQRb8ubOX6YsSAQdAa9kg8exDqR4DFfDlWKJ2Gf4BKA9BwMoAqMfC/D0xPVkw
            IZCuDI3KdTWgyCV4sNWKaKvv7KuNrMCh0pokdbakax93yi0Ba8DLWTemKdkXdpuZ
            0l4BI/SBekjbTyfu7RTRId6nq7BRsuLLUG0uNePF8AzgpjQqbARZpjjSh7j39DIN
            9vruw8ZyQ+9fO7rOYMTIn6gPE01Lf5McNWTQQ6wbCxLjFpOEh0eAB56gw5qzKMsE
            =MecQ
            -----END PGP MESSAGE-----
          fp: FB3F2A3A200A09F4DD29A381C0946395407792FB
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjxsgKazaEGsSAQdAP0l6h9UYQZPY5U5DCnh+QbOi+felnsqvWICyTb+BrGUw
            QrEziuiSX1XibdzUpXIBPE9PGiD4zISk8niknHBzeDAmbbzjWMEHbx26ghJClQxF
            0l4BWXV3boCi6jdqTTjlpk13tpEBloEgiYytlgtC4y5wB85ghEHDlPY9USRQo4iy
            jYZtRJw8vGi6gzaY2YwQ9Go6lvmEq1F/h3/545u//mCHk5EQMYWhDrRQ+p6/8Lm8
            =PF4W
            -----END PGP MESSAGE-----
          fp: 97BAD070076E18F23DE40CF367FBD7D6A827909E
    unencrypted_suffix: _unencrypted
    version: 3.9.0
