apiVersion: ENC[AES256_GCM,data:C8w=,iv:Rs4tbCjHb2QODWXoch4jQHqCt5lx/iuobcBbAB08134=,tag:3N6pAOKhdRJF6Hf6ZhDIgQ==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:wVYHQB4sPrQcE3Apja3iJZUvS4Es58BS9Dkkv9i5Nuruy6J4GsUICgow24uu1RX7FGy50KeS+aZpEPggu9uOFhUmfUwyXfIaEq0OQHenmqDg4+GgT2wdo1e0m0PBXmhEXZ6lFdh2REyTk1hsKkZVqHPDt5AFP8VIZqtcghK6e0a0PWV5BAKeygY0l3Thm+5qR7ToJCl+kWBSVCabf7smglw4mARX+/o9Ro1vFOSRnLT3c3cOWAPx8kBUwbqY7znRAwgYBAIA4hdrtEq3rV0+3Nozfb1sbz+GhIT+aCDOL1nvEV5JRforn3O54GeGBgp4J4JrIwhM34bXv8i1MfsMCqa3OFzQ+Iub/TZFBEXEugY3MeKYQCcCaMQqhFkiQ4MgRuH08dzpkW8LuVs6itAnKLkc+rVfDcmXQf1hVSJ6be0Cdat/Fl4i1ZJJsMQfdhNLiGJ6dPZeQ6uCk3INfL1ES07/1fHxhLKhxFm+RSzWMG/Ur9Z92+isEsuEtyoMepmu9at1s9vZNMd3RwP5w4M5v/C7LrRvoDqwkWmdeJcjQ07muZL3lX99Sd0tSsGVaK8WkQy/eGbUQN21BlOnVPZFlYxXWPS/wZRr6+Loc2DAToaQua8Z993LbHqjqMRhNL+Lq01AHVmvmzGsaA8M4XbMBjyz4D0KIV+oMYqOLfLiX0WT7Thxwgf6O886sGWvpoyOplRMRKR6w25vvQ52eaxMWCeZPFGCMZY0edQlE3wEYVzDMRyphNOLxtIsYJiBG5dVnT8lsqsm8lCyKhvQEquPlFnAh2lVRq4t/Valpz4M/RfqEhdjU+jg+DhcwvFtfV4uTBPhdKvqZ7k/kcH+7+CO2OrnE2VpdzU39OG9cIvdxZa/Qorkn1BIdM+jbRIm1EeAo4W9FdNylF+GqrUuBt4WEUMYxjVR2WKt950iMf06zx6UaKDCvmpDtaXmtvbMCBtgoliQnCCLQzbfJ9rzLm5n03/0eb301jP5XQWq06e9Qpr9rrxnqaDsCqzbLVyfNKI01gdDMmKNkU6bguHHrQimMFr6a4GlN1FwtCJoxNdHWONYCSjxUXzfcl1eYKuHgDNw1YnXrCPjHiz0ZguyQvf5ZDQZl+g4Fes2vymLsY0CHwOoFfee/8PzCq4QYw+rtcFcSfP2BlvysLeyDGC2+cKC0d/Kgt92xflS+qm3DXymBEiGHy6Cva2PsPyNwcGVkOnM+70/0v+DeSkUV+iKxz9H1X2pMwQ9I49ogPxMCCbtUji29rIhAL2K+HY0nmkOgRSBT9sPwI7ko6+ZKjLE2c+xdabBRkeePJrC+5FUGvoIM0tQdKYsoZP66XjZlJIu9os7X/Krvrmes2NpX8PUqGMibTi+DSgtmfm50aQxyonkU5uECE/cGI7Tu9yvJt/0hi0GtJpyp3ff24Yo2qHsBBoDtC/8nWtglc6gcGmCEXczAoClP7QWQKSbC9nKBJOWDBTfBkI+lGxvOMohvsQZbZSNn6XPvlf7DWneeKWsVI9b5bFe+2WW/496tKboSjyMSm/hEoygRSBSabkMwhlGFlv18/7V6/UwF4MP1ZuTauGWbj1ZbHfhsceunALj/1N4ToXV+mt7W+2cxxrzUMjlae+pMMwkTaTuYnWrmsGUJlG/tgR1xRHeV2yakEmbdb6STAPmUAtaXQl6cB1qsVYRaFufgpUBio9kItctXRKVc2J/zthNAMxoUwkK0TrVPsW/TteWU3gpKBCsMyKh7ztsd67uAYhCBZL3VzmzoiGw0VGscCmN4189qyVGYP3R4MFt/MFwB7w7cMAIIHDQiJuXadfKmixAo1f9NCcYsj4eNvcKdRHFeQdeslGaAblTd+btz15f7ZTiZuLoeltG99OmcJq2cY2IW3ceuxAkyOHbLzSInYTnCGKkeq9ppNBYmDFZa/agz+BIg88xPgkAMxPNXeU9T3eYL8rVwLXwbUvlNGXiKMdhSNS5,iv:xFnIb6zQ31dM+hKF8PAJGla6LwbfvPttlUGuBbHsZ5Y=,tag:bPK70aQdtN56WqjJbaH0QA==,type:str]
        server: ENC[AES256_GCM,data:WfxtMwWugx0dxcbbjcFip1fWqWYLHnGr,iv:3h8EMTswS1UCikYnLDV4W3dxYN5eGj7Vdk9I2vPcNyo=,tag:sFBr2u7s3Ww+IKFQJnFVrw==,type:str]
      name: ENC[AES256_GCM,data:PVMLaDDjxT1V6VJv+mI=,iv:6AwGAr8/XUow7m74wVD/v7LGtsqJB6gCUjAX5mbZaKs=,tag:Kpl55mDNRNydhoHc6MNVLA==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:HRJHoDa4oajvcLR95Ho=,iv:H4b9P/vjcnlHUdfJCUflJbSQs81dHF0DvJDK1vhqw0Q=,tag:QVZBr+34LRQhmNmg4GM9Vw==,type:str]
        namespace: ENC[AES256_GCM,data:CvYpCUJm52Mrh5TTYDYKKH3I1gLEDDzBDIMP2g==,iv:SZZNORD2VjEYKIs9yGkc56WXR7ZkvqTGjaeZo0xYdnc=,tag:UHScxTYHmdiTt6hlBwsjVg==,type:str]
        user: ENC[AES256_GCM,data:kuTaloAm/JV0qvWwPG7Fr8sE,iv:cjHlOHveOcIO0vfJJcCsZIMMlqpCEoI3gBNLgwVBNNI=,tag:f1KdtgthDBXC0reN7ChFQQ==,type:str]
      name: ENC[AES256_GCM,data:PWCL2s91+D5Q7rRPprh0RbXYhh+83BZpqQH4+jhYH9uBK+8=,iv:P2jkwuifLjBmo1zlddIfMs7u8PSWKZyJN8sRM8f5OnU=,tag:yMglJU4zysBBiD2NRrx98Q==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:HRJHoDa4oajvcLR95Ho=,iv:H4b9P/vjcnlHUdfJCUflJbSQs81dHF0DvJDK1vhqw0Q=,tag:QVZBr+34LRQhmNmg4GM9Vw==,type:str]
        namespace: ENC[AES256_GCM,data:KhJ/ZoGu7F9kpeaRdh7aWsCnsMBCizmjTO/Cu4x1F20tYmLc+H4=,iv:l6pjrI2HxZjS4V3SfrZm30B++V4seaG6W7D5QOOMQhY=,tag:sdISHqnxWyDkaS8XlIePmA==,type:str]
        user: ENC[AES256_GCM,data:kuTaloAm/JV0qvWwPG7Fr8sE,iv:cjHlOHveOcIO0vfJJcCsZIMMlqpCEoI3gBNLgwVBNNI=,tag:f1KdtgthDBXC0reN7ChFQQ==,type:str]
      name: ENC[AES256_GCM,data:l/pjc/6QDfbPT4dWnsrKz5if7FueWzOIviorq7WfwSQC1Dz2Khs2INunPa0K,iv:WlS/hYn77jCbCIYVi5gKHMfxTfpcZFlg7B7gcsyQ7lU=,tag:x0XW3CvfBtAWIzsR8v28cQ==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:HRJHoDa4oajvcLR95Ho=,iv:H4b9P/vjcnlHUdfJCUflJbSQs81dHF0DvJDK1vhqw0Q=,tag:QVZBr+34LRQhmNmg4GM9Vw==,type:str]
        namespace: ENC[AES256_GCM,data:MpvcbKiNIpX8XhLZIhAWyWaSGNNXL6Ef/w==,iv:zFwp0/2fMerR2h4AlVSAum7bzNAN3/PaR5+Q1+MLQrg=,tag:/dKzl9srCM/IZI8RwDYOUg==,type:str]
        user: ENC[AES256_GCM,data:kuTaloAm/JV0qvWwPG7Fr8sE,iv:cjHlOHveOcIO0vfJJcCsZIMMlqpCEoI3gBNLgwVBNNI=,tag:f1KdtgthDBXC0reN7ChFQQ==,type:str]
      name: ENC[AES256_GCM,data:8aDT9LBhSyig6Mf2aCAWXGJW5Gy4FctRcY+SBKYDL2k=,iv:+XtB7ufvcQ9SczmGYYtaPO0M7ajc8geLsT/WsHcG024=,tag:5mo0pv4flNI03veOiiaokA==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:HRJHoDa4oajvcLR95Ho=,iv:H4b9P/vjcnlHUdfJCUflJbSQs81dHF0DvJDK1vhqw0Q=,tag:QVZBr+34LRQhmNmg4GM9Vw==,type:str]
        namespace: ENC[AES256_GCM,data:Hg2fzpWTFttGn2psTuU0SJVleaM8Xef6xQ==,iv:YpaTBBWrNHFXMKXH1SyOxY+lKQFFnAS5DRFwCyHF5Lc=,tag:xvh4K8IZYHLtXzQbsycopQ==,type:str]
        user: ENC[AES256_GCM,data:kuTaloAm/JV0qvWwPG7Fr8sE,iv:cjHlOHveOcIO0vfJJcCsZIMMlqpCEoI3gBNLgwVBNNI=,tag:f1KdtgthDBXC0reN7ChFQQ==,type:str]
      name: ENC[AES256_GCM,data:cFG5z36Buxg3NWbQ1whhLEfnTHZHgvlKdwO6aiPHR+k=,iv:tJDsPIcViajxnm+isxo4NbI+XIMR+kj9jCivGCwse4g=,tag:kJozdjqyBSQfLlPSHPSY8w==,type:str]
current-context: ENC[AES256_GCM,data:g1RCTTcgT4QVepYByzTeYfKYHgdKKBAW0CEVe0YdShU=,iv:YwDY40XVXwXKTMrUPsVDW7ncnQguVCvYqtmPL/IsEr0=,tag:wUBHzCWmil3ShpfQx6z3RA==,type:str]
kind: ENC[AES256_GCM,data:iUXZnTFl,iv:iZjx5GY59O/0etFxthpoYY0oXgpf+YWd3oSCe/ttzNg=,tag:QGLSqYBSHTM+0xHlCZ7owA==,type:str]
users:
    - name: ENC[AES256_GCM,data:OrrDU3SYdqnUwK9GHT6GhiOM,iv:ZY4o+J5fWO5byJJeZfkEnrvY5JKrUwBjsYQxhQKpS1c=,tag:A3hFpnDm/Z2jv6oT+LisdQ==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:L/UL6s4Ca4vmkM9YMF13y7uxGxJeoCq0oCav1PUiWwEe6ZG1oUa+uyOYWkwpn6Rx93Dgpj67VlszvYc6IJ+6fJ8v+aEEZ9TpjLMCeTMT7MIICebOkgOsoo9yNalI0bz5gE7m9EWpKAT8rAVKkvvk30TUf7e8PP0aKKXGF9XPvRg8JggeG61GJweDfWlQbkbVkTvsm2N3nW2lUnwYSWp0kQPA1nOkD3mJnfkFQhTjsQ3KAy3ajffgtNQzabsnmsLke4geUDuQLOHBvj/fXUl+WOVO9dgnfbHwY9xjjgQmrVNIOUH59YJ/91NIy6K12K0A8xk1O2QXhpV08pqmn4o0oJfpS5pQ3eoXoB/sgMGyK78plO8R/FoPRE0QvB1M8PggUNrWeBgptEIDFE/URh5+9bh2a4MrRaMvNOHkrzs3FVQ0ZnAZ4CAo7Bkgg9/4n5+LIPbv11KAwIw9EmPlTps9N+r5Hzgy/CJPL7sQVLAtqzvpjwMOQTpVwnMmMhf4CY2ekkEEUlyxf3ayrLazswfNeKuO3IvsOCB3POmmUJHPGOnKt+5s3ZmqDKgkcGuENobTHaTYCf97m1QmA3BSkJrDXIF7R5QBVMbQLuPP3xmaMAx0VFrtphVvQXOvNCt8NVEJd7D71xXfe+PFm6gj41l5gcfG985Zo0bSmWPPwpvmmn/Wych1DOyCemn796+BuDgucZDV8pFCDUczF0r6x8UUoxlEGgP1rhbtR9IZmupCf9ZPtXwl1QqlCw+DuV+6uIEiggXckKiUEJLDH2G8zn6Ft8UoOVo2XjLREbrhw6wLeK+bEj9uQbbwYnJtsyltk7ltx0HKBEuxiLkdM+FapGg6a7S6TYM/dCcq/6A+pWvqg3vZni4iSSZxI0dhCQoX1TN3yxVztkQkB4bl7LyvJKLBz9TMt10/0jv8+aDWc4vfNthgtPQIOXH7OI46/zQJoMUYumgcI/31UaYRXh/+T2QzAAMsnCmXioEcIxsvvq61FaxJX7/lr+5xs45z3CaSdN+ESaMM4GODlI/rqUjQo3Etx3OoknQ+e/FuNSCYUOi7fVLmyILyUSZ4q9AQcUffQ0ybGS/pyLKyRjeR1IywBZtcZXIvPzOsMGI6j0JUaE8Qmd1ng8/LHEm71Zq/bDzRgFGLZ+vYDpLawP3qT15Ie9XPuLw7Zzafkkg1EMXwmZg3WKB6Tt+lav40JuFyyDkfqpPlzj4j8+Ztnhx34QnNOS3bQSwaWwz4H/39PM1JLcaiIrhwphBJzrwS/hfMnGaGX84cNrNuIWAyDYLYyN0xAJcWqEXzwDnttXutb/uj3lnPq1e5MId5clU3UihQy8cAEKFT4wJNpdzpUBi5MyIiuNKmyHIGFmEwAUEFZZAMSfQaDI1LHutFpsI8xQ==,iv:CVTni2CbqU37+DyzN5oEnNRXEKDGRq7Yy8ckDdj648s=,tag:d04hOsbw4d6DvG6ovw/R1A==,type:str]
        client-key-data: ENC[AES256_GCM,data:xRDUeoBd+VXZEPBSUjUvf6UTGTgxqPqftGK+UxgS4kBGI41lgLFV5jren3o7JAWOrmtIIsoOOeQvCBU+fye9XyKv5mltYzDJYuD7/lhFow0Mqdd0ZKf7vpSnee+LARBGlST1XpKtXjpS3Olafat5yFzonP0sQN0coD9CDGjombNXNQ+aBa505R1KB6uxfG6TsV+lBYKr35/sjUoLmE4Nqg==,iv:h0dsleumARfJDCC/0EyNjIAcHX/gR2y/e0V/RRWH4wE=,tag:xLOKnqaXb6eJqL0DcJygwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442vmk8fl5nxrejuj0g6a63cqdw7q7ufvnxuqf3wcsnetgmv2phsl8eufu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva0d4Z3dPTFlQdEZsazhT
            N2hobGx1cFFVMEJFYWxuSmtWUllXMVVTa1ZNCmlPb3g4a240M1VJM0NlTWpUQW0x
            RElOZGNJdVZUTE96ZmlsamY3VFZVcGsKLS0tIHFscFVXSkVxVitvWjBVSmNqanlN
            elcweFh2Zm9Xc09PRVlpVWZJdHFHTjAKJ8AXtMvGFe8g2Cy1PXvVQCNpgahztBMx
            qjd9QPC1N/hlzuc6sYx2ws1Z6Ca6ho8oWJ5NAyB3SIg9CTAnATKBpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T11:53:14Z"
    mac: ENC[AES256_GCM,data:orQYVSqmPr2aTgZtpvtWQFSTIiD2158Tvl/Eva7WExQVKQK1ebEkeEogFDuWSfuW2JzEnJ5PQ/pA3nuj0iyPq9jojrpdvcw+bXiO+/Pd0vZfngItu2dG/OsBVjMAQ3CZmp/fZphtEpBgI+RO6/xGsUvXqVmxP3Qd29B6ykDla5U=,iv:JMUjQlQWrxNKC+hO5Afx0Cf0CVsbzpvIFSlp0/OO+lE=,tag:qoV0UHue537xgc7J+4gxqA==,type:str]
    pgp:
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3FtoE4fF3lxARAAq1qh8PiyISH24HaFlFN1maWUeQ90W3G1LPTIl0oNSROb
            W8cGPrGX971YfZHyoPP0ivA5+TVSzlLiYCKSvvdxngQuoOLQe6S1uihcCjj6ZQrW
            3e+EYxoVEht1TAf09AxIuv/uxn6CZ4dte5tRXKMq5qt8xwDY6nRmr3nmQcnvQXo/
            c0rHYb8AgwakS6bE48vft9m5whd2fOm8Dg4y/iaMxujflkCD5UMTfJOqKMeLt7ur
            fggyrwOXwlCbRRJbfWySHvL/mlXyivbuobZ0+pYdxJDvDP8s3XWX44Cq8vVJfjwa
            zednzJoTh/6KHM1jCAFPCBtMKMHz2nCQH3ELPPZk3dFXd3mZSfRac8DU4Wet4owf
            JpjPB88IVvXF8T4xa34PAgfg3MEOROmsWSxgbDWC/UOayg9ZSblfaY12C5APPYtQ
            BcFx6cQWnihJJHmgs/OAp1TRyrg+x1xxqzhcYyZA/miNpzyy8no4B1TU+06nwLJ0
            YiRqItfOXRCsjqcjX0fqzl0/uq1H+SsjwN/ctWSjWsl5ZykSmGMagPEM8we+82r7
            sJpj+oZepnE4/8wjwl1rupQn00NGUz68OomG3AcHG5oyUlJjwO8RlE6q4ezJOmEb
            OOgniyLRYjLnl2uG4WG4JRtGNCxsEBjM7u5A9/QZcYvFWZFHqk9CFIUMDCkkSmrS
            XgGk7G0gFJXwv7ryG+6bOy06loF1NNNK8qEIFdZhzeu0WAngis++syTZ3kJDoe7x
            60oLlmEvyw4y6dJ6i4xlTVloUrdMYp4jCZuvjecmzCz/ZCjLah2ZwIIK9iIjXo8=
            =DYGe
            -----END PGP MESSAGE-----
          fp: DC8231FEA934DB14D402E72D3B6555ADB3910EAE
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0NuJZWRmFubAQ/+NRgkQb7af2Ik9p38fRHrGkndGADDOrRKOu2zTn8CiHIK
            dO/a9C+kAIVtkCuGjs4EPxDIniZtrRq1RJvcNqZtq1vS08zVw6K1u2KbEVNJjY7Q
            OKRJii6j2Pi/6gl0/AFkssdCLoVCR/UAw8Tz3wIEHfQt7MmPdH+7uWl1CEL7r6zJ
            0JDIA28vgjNO/PvtcpLpSa14NmKXVTKptaeaEczO3s38rD50yipXSi6U3rLYE49r
            x4OFs9rMCcLgrliWhA/oEIznvTmWwMzVlWfiGxgUOWoh15rHOMkmLfMquK6Bzz+h
            nG+pfqR1RcjiySsYCuDx8fOu2pi7bYbBqy+hyAPK/4snRVWq+bujEJs86ken1pJZ
            nTFe3Xg/xALr55bOHImtxXGtGwyLKN9tOsnGDUY95N2MYjVkMmo5Ftn7r5rUklQb
            EamCTE8AU73TcPsbJ48tJVhnEAyjGSnbyYHNlBp84gDB4QhGoXyWBwfPQACTtVvf
            j/haqSWaH8egFNXhzQ4rmTT4zfpVmAY8jaQRsTDh9K1GOlTxLJMAXMpO5jW8wWDM
            plsWozgUwrOm/ck27oNUNo0itiQr/qJG5kw5/fP4XROhXavATKW41dUmdehyu2GR
            d1WI4/X65erivU2NrATTwpLeyaoWpAGT356lipebgx/3tPSJg1jGDtIo6xcLR9rS
            XgEm4Un87j1qIarxcJT9XUAC+WvhpLAkAkmJi326uEWKoVSbk9K2FJVb+INsfWA4
            rmmI6qve9CWEZdAqOgrDGfRbgPj3ppKeQIyXkHkcFunA4c5UTnUrTYaZMF7rNVs=
            =8VFN
            -----END PGP MESSAGE-----
          fp: 4CA6C33F1261AC9FFE27679791A3FC54A5E4B97E
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5jdJleHfCY0SAQdABQSAnCFDECOWk7ZOHFkqQBBi59A4JQuBQqfqzxrH3gsw
            gC80Amcnna52JYRJPmIpK75qXLHQtZXU2U4NvpLlrZFDjSKm2/IOk6qFQgY0Fgjt
            0l4BtU2OcHoT45QHuWmcwV26xrARtS8dKO51juoCEmtrDl0h4xc7XozlbG2dxIgV
            QQzDjbB+G2kJKQM9h+7xv2Unm734AnO3W+uxjjI3ymK5ZWCwhEaMiWpXt074wdgg
            =dYCf
            -----END PGP MESSAGE-----
          fp: CC7B10CE8D78010ABB043F8DB1C462E90012ECFE
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DQRb8ubOX6YsSAQdAa9kg8exDqR4DFfDlWKJ2Gf4BKA9BwMoAqMfC/D0xPVkw
            IZCuDI3KdTWgyCV4sNWKaKvv7KuNrMCh0pokdbakax93yi0Ba8DLWTemKdkXdpuZ
            0l4BI/SBekjbTyfu7RTRId6nq7BRsuLLUG0uNePF8AzgpjQqbARZpjjSh7j39DIN
            9vruw8ZyQ+9fO7rOYMTIn6gPE01Lf5McNWTQQ6wbCxLjFpOEh0eAB56gw5qzKMsE
            =MecQ
            -----END PGP MESSAGE-----
          fp: FB3F2A3A200A09F4DD29A381C0946395407792FB
        - created_at: "2025-08-27T14:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjxsgKazaEGsSAQdAP0l6h9UYQZPY5U5DCnh+QbOi+felnsqvWICyTb+BrGUw
            QrEziuiSX1XibdzUpXIBPE9PGiD4zISk8niknHBzeDAmbbzjWMEHbx26ghJClQxF
            0l4BWXV3boCi6jdqTTjlpk13tpEBloEgiYytlgtC4y5wB85ghEHDlPY9USRQo4iy
            jYZtRJw8vGi6gzaY2YwQ9Go6lvmEq1F/h3/545u//mCHk5EQMYWhDrRQ+p6/8Lm8
            =PF4W
            -----END PGP MESSAGE-----
          fp: 97BAD070076E18F23DE40CF367FBD7D6A827909E
    unencrypted_suffix: _unencrypted
    version: 3.9.0
