apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: limesurvey
  namespace: fairagro-applications
spec:
  project: fairagro
  source:
    repoURL: "git@github.com:fairagro/basic_infrastructure.git"
    path: helmcharts/fairagro-survey
    targetRevision: "{{ .Values.limesurvey_revision }}"
    helm:
      valueFiles:
        - ../../environments/{{ .Values.cluster_name }}/values/fairagro-survey.yaml
        - ../../environments/{{ .Values.cluster_name }}/values/fairagro-survey.enc.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fairagro-survey
  syncPolicy:
    syncOptions:
      - Prune=true
