apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-middleware
  namespace: fairagro-m42-applications
spec:
  project: fairagro-m42
  source:
    repoURL: "https://github.com/fairagro/m4.2_infrastructure.git"
    path: helmcharts/fairagro-basic-middleware
    targetRevision: "{{ .Values.basic_middleware_revision }}"
    helm:
      valueFiles:
        - ../../environments/{{ .Values.cluster_name }}/values/fairagro-basic-middleware.yaml
        - ../../environments/{{ .Values.cluster_name }}/values/fairagro-basic-middleware.enc.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fairagro-basic-middleware
  syncPolicy:
    syncOptions:
      - Prune=true
