apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub
  namespace: fairagro-m42-applications
spec:
  project: fairagro-m42
  source:
    repoURL: "git@github.com:fairagro/m4.2_infrastructure.git"
    path: helmcharts/fairagro-datahub
    targetRevision: "{{ .Values.datahub_revision }}"
    helm:
      valueFiles:
        - ../../environments/{{ .Values.cluster_name }}/values/fairagro-datahub.yaml
        - ../../environments/{{ .Values.cluster_name }}/values/fairagro-datahub.enc.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fairagro-m42-datahub
  syncPolicy:
    syncOptions:
      - Prune=true
