apiVersion: ENC[AES256_GCM,data:vzU=,iv:MrsRuBRABlo1wliGm9WKyW87HJ5zWpuogkHdmsGiaM4=,tag:EqJzVEKS/RyNN6LHEQmaqQ==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:zJvyY9YdOYc7TC2UYTFZ+QuNy25uzDaVeQAja78D5IwDMOBxk9xF0pzzm+iouPKDPGkU1oDZ7u5YTytQjmoU4pMRJXDxLG7lMCo/QKwd9dKyodBDX+Mfkb049034hc/gpU2gUCqF+9JfgIm1CpSAg4oz59BVGp1uK/478hwhO1VRO+/WYWFw0zXMjIJm60h+V5ruP20dCNv2HwFaklHKYZgSpPntvr0u/ZmpPKs+vbWF81mzaoNLWVfbMCv2UsgBXrCEjbhlPVdQQmle1AmgphWOAzcRkv/c7Zho4C97hZ1PUzSUslzWDYYM7Dws7LjX/nU5BWv9TDMercbYJNA6aZzfm7oVN3lgrRsfTC19OatYmTlp3rJtDlqIFGECt6+ghQ/HBP68Eit/wQM2xWolWfGQh1N0EmSfkaRE3nNz4Rqzs9oUehIJjipX7We2hy1zlO2ol4r/k7X65pHgG5RHVWBooIs5eSzHZhQrkNKbTrrKs1bgd2u9dNI2qi5E4gR0Xwhb3q7+h+SdVS/Itd16xedLdD7wX8On3yJ4Ag5xmU4VA+wuwBGBbEiWEB331QITvR/ZaiSvWCOU6IBFRrsOV0tmrh13oyxj4n59sgo3fMu0WndQY9pBCh3QisttCdYRvxRTdGgqGLkmLvMQ276/YkKtKspyU6kAznebUtSpzMYLOAc2bD8Ng6hvhy5J4ueLRVjwkA5w9bGovVMFzQINmXT5WXthaoviCdc0umFRwHEOIcLlKwlE3wqv2M98kZ9T4SXYCEXkQ4QM8j0fC7i2Y2Ihl7Nl5f24dVcve+iyVdor/SQgW8tE42nar8fddExNDYyz93Gal/KuRr95pBM0UcsJgapEUBELExk6sUsmct1VtyduCTJPLOeFstye4OWiUB/yNxjwdUcLgbAL4G9q7pH++r09gdiOyLd+2nCH+KGW1kXbxnbZ7FqIQmxXnk6ndP7YywIzaNRlh5bvNgO83KTyQApZ0qAHLcZWh8rbQuFMkTwqvvmO+pNnb6ynHbzjDn1+SqelhR9hh90VtqF5AHl9ToJVd+uKdJzLcyov491xle9zoX0SqFSFJxrwhT13QkqddZJL6uzyID8EW83I/kbVrHuj3vyvqnu6KZtBuQIiY7LiIS3PDJAPn9VcuHWnbOohGT54S0bHWF7jMpPbXpo5azc2E7QUCGA2NuZtfAK13TbSCBwBFFAfgtigPyniibP2OUE4LR+fO89SlrllAhXmd60tfZEtflQHUHEwXn77nYZ6jNHx21h7glyugsOCIAQZLLVNrslnYsnnL7b2nUIOECLMTpMgV2MCM9TiQcvMUOW0ikdkXybLRgfIJjESjimu6dzTUjORCY/KgbTWR5lFLSINJ+D341GDl/6AIkpQ4MChKolHg/VSO6OBrXtfjP723RvDIgPtNm9b9fw3JxnPFbwfQRqhkyRYkYUzrX6G3+EM1+uAbz8uhneaXNM3QmiAUo8yzw5LEsZTeA1yHi3yeMrKYYShTeYio0yJ6XPVfQ/ew/BYXzCPjsS9gnoCz+vqlAekBXkxymHT0vwixur26pYVsEH82rnV7vnf7XSs6jnrZz5z8GA9V8h3jtrBI+d3+/IWvhlCsEgTmlNtgW+pg4y074oK6iT1g/Aj/873vhjn0bD+uMX5NpyWTqxlMcRnDM+w8AH6T3ayp0qsO0kHTUXdZRRGNnqDlmrzM8/7WSefvJFLyr12TsOnppSpXnQNF+JEknEbTRYLB7LqHt4/r/psbcDDcaGw1m6k8j12nEfnEuLSGqOnaR4wRxiQeg8QiqAMRfvkwwOBOvI9yOBtxGXmkLZQE0US6zD18ueRQetJz7Zn9ORO9PSDL4ByeIMt5L3pY0WyB9NQeU8eCT/aG1FX0OaQqQWg5K2FMesNG+/vC90jNkkQfim57kKHQeWXv0VTRapXDpRwL6Ta5p95Z6hhogVvzXFRV/nAX5OQYnN0,iv:5bbW3bAa/bgw8NiuFl9V0NA/sE/q4ykg5u8U95bXZok=,tag:E6oxBW/h+RXk7WI3rbcdHA==,type:str]
        server: ENC[AES256_GCM,data:DTSV8bjWs1cYNL3/weJG/9d8wvc2EYXPcQ==,iv:A5aZIMtycTZzlXjFokO+QVdmWNUv02xDBknlFOR6/DE=,tag:+9V05NsDhz5tRtHyme9gYA==,type:str]
      name: ENC[AES256_GCM,data:D8hz3Rii3siUfmxR3Q==,iv:Q0ThmEbAJOlhCJvShYcsZiQJrVwrpyhWXWP5+hoQmVc=,tag:c/vonLMMDwc/XCMsOYgv/g==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:5E7Ssw7WtwpjGMhLiQ==,iv:Bmyr2+RyOlh/S7INNuLlL95GQVPmnEUufGQLhpA1io0=,tag:8rLvr9vHryAX6uIZBAsEmw==,type:str]
        namespace: ENC[AES256_GCM,data:y29YWfU6s1A8y0m9GWRLQYzyrpWzEUKd6HPoRA==,iv:y1FcRkvI8D81PFZVh/N/BVjhEZ2B3rnm/5CNTb2C4eE=,tag:HiP+tIoqKJjXQ5sdxnoCSw==,type:str]
        user: ENC[AES256_GCM,data:oilXuSMV5Fms/hqf31XJTuFD,iv:v8C+OTLpHLl9r3sqlKdXShKM1HdjDIdgAbPg4rjjU0c=,tag:j55Sqgu4TA+X8A6exYz3Eg==,type:str]
      name: ENC[AES256_GCM,data:Oyrr+ANIWCEPew7DaVCVxBU6Ar6qnMAVdfCuFlwPNYdFDw==,iv:t3NLKOUqJJTiNsM8BaHHDs0EtiKXBZxTOuYslGV/u8c=,tag:144g66/JDk8XWmkYsg9TXg==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:5E7Ssw7WtwpjGMhLiQ==,iv:Bmyr2+RyOlh/S7INNuLlL95GQVPmnEUufGQLhpA1io0=,tag:8rLvr9vHryAX6uIZBAsEmw==,type:str]
        namespace: ENC[AES256_GCM,data:aheqOeNtmE0Gv8JPUayxa2ZDQA/nW72UOuUeYJSnOfRkuiJ/ILo=,iv:kUfMaCY5i58zNx22NBj7+MJQ0NuhQmFBfjNQjLjProA=,tag:KqvUwQlL2Ohlmiq+VUMLgg==,type:str]
        user: ENC[AES256_GCM,data:oilXuSMV5Fms/hqf31XJTuFD,iv:v8C+OTLpHLl9r3sqlKdXShKM1HdjDIdgAbPg4rjjU0c=,tag:j55Sqgu4TA+X8A6exYz3Eg==,type:str]
      name: ENC[AES256_GCM,data:Pn7k09b9dRyBvHX9bngWq+8y4k/JJ5Foy41xtE9c05kpihblVCD+hsu1+GQ=,iv:WjlQFp+IRlQUatd/YTKSJDmV2QIUgiQlYbb2IJJ13Vc=,tag:2rZ0DZSmHsGrNwwA8zH+CA==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:5E7Ssw7WtwpjGMhLiQ==,iv:Bmyr2+RyOlh/S7INNuLlL95GQVPmnEUufGQLhpA1io0=,tag:8rLvr9vHryAX6uIZBAsEmw==,type:str]
        namespace: ENC[AES256_GCM,data:21J3BVZcvJEJmC+vA1MViHY1ICkadKd1vA==,iv:Jgulbdz1jxicHSXh3Q+BWBPfKNwV/8qSy6NoVvUMCmI=,tag:7kcKCijFsCVN2QX2Tfq/Dw==,type:str]
        user: ENC[AES256_GCM,data:oilXuSMV5Fms/hqf31XJTuFD,iv:v8C+OTLpHLl9r3sqlKdXShKM1HdjDIdgAbPg4rjjU0c=,tag:j55Sqgu4TA+X8A6exYz3Eg==,type:str]
      name: ENC[AES256_GCM,data:TbBWzpjlSq/4u4AsyjmXcxrdDTwPj2l8nneplMQGCA==,iv:XmhI155eNWaykwHF+fabtj4/f+kggOY7SzL6koyei1Y=,tag:Sd7gqs/S1O63u+s5OQ1s/w==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:5E7Ssw7WtwpjGMhLiQ==,iv:Bmyr2+RyOlh/S7INNuLlL95GQVPmnEUufGQLhpA1io0=,tag:8rLvr9vHryAX6uIZBAsEmw==,type:str]
        namespace: ENC[AES256_GCM,data:ssUx7YwFsEZDERWHna0SlwnDIJyLmXyDvA==,iv:VRD4J0ytkeH5Qsl4Uph7FcLN7tYKrZqLNHC4vQHKZrI=,tag:mpsg+8q2t1i7p0+q9O928g==,type:str]
        user: ENC[AES256_GCM,data:oilXuSMV5Fms/hqf31XJTuFD,iv:v8C+OTLpHLl9r3sqlKdXShKM1HdjDIdgAbPg4rjjU0c=,tag:j55Sqgu4TA+X8A6exYz3Eg==,type:str]
      name: ENC[AES256_GCM,data:uZhFGPasYsZgIdCybfiYKJS6iy/gmXAIwiYVA7HfZA==,iv:4ZwvapwD4+ZEcR91DMnfetVK5PTdK1hS3OiRCnhE6UI=,tag:jD70OtKw4an7mIPAlBL0kg==,type:str]
current-context: ENC[AES256_GCM,data:WpUdv/cBR6BgTTx7JLX+QHUYB9vJu0FjyduQjxD6+A==,iv:UboKTcojfT75LdUPGBERdVV2J7g8Us/rscmlSxPIB/A=,tag:57MlyK1FLi06wbnivd9ZIQ==,type:str]
kind: ENC[AES256_GCM,data:CA+fujP9,iv:u9h1n2EFgAd3wBOM86NgMltX30TbOCvzoS2EgnSz3GY=,tag:Ci67kzE2hgXkjEaf0Ls/xw==,type:str]
users:
    - name: ENC[AES256_GCM,data:xno1ZUv5COwOvuObdGAxJJln,iv:OTN6EdSDlqEArk0Zlt0DD4x4jpq2qFnQUCb/Od2PvUs=,tag:4Mwv3NS64j92oBxVA5AhjA==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:thxkwvFJnHGleihYTKL8ut6RJ3vGpRF36+SvyPLN4AU9pOIfq2yy93I+5ofxWCHRBJvI2nNogDfyB1T66QQOfwk4FXjDcHb1NF1frWpUwlAZr7efkD1HjVyDn8iRJ89BI7Zl9Z7E5NU8Hs//Wjm8KMfH2tNOt+IaoqoR+nBz9V2+3Mqe2FAhZF2xgRAynRyxxsbHXgQ4YgCgrNBbs46CUpa8BOgR8XeZMjhOsqRN/oj7gLGyNn4UjuGyNzaFmMSCSZUXPU16AzWdp76sIcB+oMMluVGV5ADC9g6GlFQga2pc2pXQPaBZRnoz+BVOEdZWyvIxZY7F9bbDG1uJJFK5fW0cboyX0q+Z5cmrRecgj34f4Bdh/THgX8fQmedT+135fhX+Y3DupmToOkzOst8vGuQ3c8hdYB89w0sjACSVXdAMQfT0otldY2aIkv7hxxRjsZdDw+I/qp+gtthioSkqgHRas/k9QiuqOLxRByla4jOiOLAvkx12DjMEegM2beA7OcpLR0s2Hj481bF7loipOaUhunD4yngYJy7/jX7cOOMYljft5AJ8x0E6OFFlNtCvPyd6A711zfyiItYWKxZ9QsySMGR9OkePK3hhdsXIX5QJ66o9QlSQDGdEgNdFO+xR9cToQAv9IyAezxu9yoYlWskC2ivCLXTMB8IJyaYfTz9dVFkC4XYMt6Rt7UE4ob0g6b51kMxM4vmPuU96PgTZyLp67k9u6RV2gdBhCZK+M0Gk8cLg2j7thtkV/o/uLCei4vwr6/hqHa+qaMTAMS9z3bXWJGOjqEIcj8KwZTbI+RpYXPX4vq6f3Jkr9kiYgVKP8WeHiwLZdTSRlRGkdzy/4j0L4zpBOI9YxJv6paI2wdXkpW/7T8bmEidrzCliV46rbVlc4LL5e0u6stx6/q/PyZEMR20Nwm2Hdj5CrFLQOS1fKwuxg+0VOcOU5JoEVs2QHzXRVdz8lm+od6iFJMuJVo6+AHZx0dNWV8jKZ8ex8Lgmglev7B4iF4wqDCVZWsTQeNubKQ1AwhrJyPKVScpf4G9ABE9Q/OIaXoaIplDtvtKkf9kSJFO8vkNk9ob1njLL5KhucuY8saI9pB5reZ9F+sPlQDcxgtfY60kv8kEnZJ81Z2Yf89Ym7sw5/Mtax+sCwyDnLctQks9f//DB9Jf5NgiINK5eptLPkrnXH3sevG3CLxoO2ptTZtx0aSfhtfUwKA4V5wOqiTrU/LIBWhCxDSLH6au1kWVBsHzyaK+s6yoEXPfB4CfmY72mORAG+qWg+TRwHu0a76pY9kbWVSKp18vGgWbdp1eA9aapdy1sr2YpUckd5AYoGkIYLpXb0Y1AHa/oZMid/EPndrPTBti40sAG0Dz23A3QpHWZHtWkMqQjfYpCkW2GPA==,iv:xYlIsntiPDxOXi8QW2q8cdYHbC+94Yp9Pc/JyC/LkgU=,tag:UHdWUblx0PCf9G1c9grwLA==,type:str]
        client-key-data: ENC[AES256_GCM,data:aGFqWthlrVqTvyZsgvqKFm5Lqn8PW8hZzeLlu9X53VDUa2kZX2mOWtWsn1Kk63+zubtv4Y66iQhyV9NyQFpkVVvOVCm0NsFRVnTc7vj6bshcucPrJ1sZJG4Pl2oUoTyl665nm4lhqBeGfdNK1j67GhrCoUSRJmt8v2t1BfrLPdjV/O1L2QMjaMtGsO5QJh7GNGuu1vTNbvWoN8JWjk/fSA==,iv:XJFJ+uprRkHhm8NI8bmWgwmNMlVDiZWU9to4IL1/CvQ=,tag:cWAlhChYr3IfpPcD3BsWpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6rxgyn83rgjr6zaws764syhy6f25hanlv0y3sq00f95lrjprdzs9v2zv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWmhNMlhzQ3d2MTR1RkI2
            VFJIVGFvQk5aSHdpMnhQdTdDRi9jYlFhNGp3CjdMbE92U1d3ZUxwWjNlcXBzYjMx
            dnBUY2hPWGFaWnFuaDVzcWJTdnNScTQKLS0tIFNsRkNWKy9RaW9GYm5WbzJDejlm
            aGpMUjF2RlVvcnVxK2lQSUhvaEV2NlUKWHo6ksG+ajeDQZS8m8aqmxoPUCUUf/ce
            W+po1UsWYik7tzrjkOkWld/VGxFu4ag89+Jb0FGCjidDMWmHc4n8nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T12:26:16Z"
    mac: ENC[AES256_GCM,data:hW9vW6yI3MijojtY+Ks/yVrS8gexXiA7bh1cRlC2xsERWf2a79+exTR60bMpFr942R+aYtE6FmInh5oUgngGVRqRSs0w0wjsrV6zTcSnDKFayb6MMPgmnZJU7XtgdWn1gpFApNCyq5IGWVM7oNEqoBVGcA6n+0rpyIAQ+g9ntYQ=,iv:2OvzyaY7xIy23gtd7hHEEjvzGHJH/KMLJvyGBPTJW38=,tag:ZybC48DepLqNyXHDt162rA==,type:str]
    pgp:
        - created_at: "2026-06-16T11:53:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3FtoE4fF3lxAQ//VKf76pIlY/OzegHq48cuwoj5hDbvUzzbquXwprlnIClW
            aHH5z9gVSH1sLmUWjsnFbNPiIRE9B7AWw4YG8KgsR60upnhUbGzUeVqbgWDAqeSd
            7m8B7a1gnkOA6D6LpLu4g+NiwCH2H8FBshJtguSV0M4mer0vpnnCIvaEoMZ7oGaP
            86owUOa2QiwQJ3Mqiaozpm8w0FwAzyxPeqhKvrfgFgcaUJ7Sz9tkv7xu4yJeEu30
            fT+PiC+XLcI2cbrIdFc8iwpDWEqxabTdG87beWahpDqOVPQiMlz0aOXNfm3hw5YM
            kx4uvcBWEOjgrJJkgBopCH2/h7rSbG0z9tyf84qZk4FlL3mecUIcWoWh2YLIII83
            oCDRm8e5wgj9DAV8pDKYQU35BzXE7Sg4JVY6UwqitmtByNaMNm7MVfdDSLBDfbyR
            AWvMWAUpqiPtKsYP3pxFmicEr3eA3Ct0ruVro4rJb8WIlCoXcFGtKS2OgEAUzVoJ
            lyQbDR2cvOJoY1Ey59d+ADzScp4fZ7BSOfzF5gEbRTe2pboKXUhLDgdFraFmY+u0
            lk+2YVkMeXXDE7ml0oSStxf8JFAb9IEpIYthluSYTeWAOSmuvCovOJHqetS5GDkX
            pUZafU5CRHmJFQagCckflskx2mDrc2ChmlvMOBrO+WJR3tHQV9Q3AS3Jh0xJ/RnS
            XgGN57b0akGjWDTLzL46K9whYzndgGy0POuIXXjhIRY4pYawb2NVXNy9TsUdXX/8
            4Z9facEDHpaZ0zW9Bh+l5IlEwIBcIuajiu4oL38iRgZn5HBQdlw6vepEzwO3zFw=
            =+ANO
            -----END PGP MESSAGE-----
          fp: DC8231FEA934DB14D402E72D3B6555ADB3910EAE
        - created_at: "2026-06-16T11:53:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0NuJZWRmFubAQ//Vk3B/OlpZK7WMKeuOjBm2YGfxcV6txARUjIgULTuHwr8
            EKqk/1FR1KTAj9KOGOj1Tx+MpuIl8cLpb+hXzae1E1U+iFfZ7mYdWrY8VqfHf2OD
            a0Cpi7UomzQWj9KqCyhRIaKM6SZ8bNj/862N7iAEI0QuUEtOe+pkxGasxBO9TTG9
            i8sJqfNijQGHws/w3pOmCKFPKJIP1Wr19371Cz0s89KRSnAbwIjt0SfH9zmvkfHc
            5SIswjIELrtI7qdJ7ELpQcGrHQS+izAYTxZbyKOPZQxWt/0Z6HhXwpuG00lLVmIC
            CgTN+sPANxiStdIm4O+uHGDfpTicI6UJor8cOI7gOnEbB+ulnY9AhkdaFXEjfEvc
            bjulHmDwTtzFLN0FoSuSOUPat0FvkrKxGRfFvAyvsVFm1vnJjG4Wrc/ItBBSG0jy
            JzDBS3sxcQ6QH1CiX+rDyZUvGlybpRzqSSqBNDVbf9KwAxZt7WfW1rCM+MMcyLfc
            pUIo8On+9gZy2xXFIyFMO+qrYCPflFa8cJQ84Jb7dwOJGD/TX/Njy85jSedooheL
            TQ0DiaFOzjcsvdodrP34idUfasg4CCDhzoSGDzRKSKTby3LVH/aDKqIcocAsz8Uz
            lGNy624g72JYnZZ8paSt7OLgIPP34Bi5IHJE79b2RpJzeJDVtND38YQkIbteACzS
            XgFOkHxcaEAK4FaJdJSsjPYoy+1cB8+pKmG8Aqptu6z/VTXrRWUQySy3hdvUVIq9
            LzRB7KmBtq+2E88mG+TM9ssFmSprW4Ez6mRSpnn3+My028LworKsY2kDcv5cppw=
            =8/Ww
            -----END PGP MESSAGE-----
          fp: 4CA6C33F1261AC9FFE27679791A3FC54A5E4B97E
        - created_at: "2026-06-16T11:53:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5jdJleHfCY0SAQdAlaAnp4yALCp+edNVLvYvaL3HaLV1n5s+tCvjDtlVs1Iw
            8djbLADniYZn46N81tWqUdzLO1bCy/wQ1GtduEoHoZASi2nN0qWhoTUGdpulDeMS
            0l4Bygf7Xt8PLhVdl1449ko4CtHP/hLEgXk7MYYBjFdqA10ySDOq1Krv3fdgYVUo
            wiMFf2u67daQmtI+59ccd755Nq6OW4Y3r4AKp6yvfDThn4JP7BC4gW4SxnFG7Qqv
            =p2Ur
            -----END PGP MESSAGE-----
          fp: CC7B10CE8D78010ABB043F8DB1C462E90012ECFE
        - created_at: "2026-06-16T11:53:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DQRb8ubOX6YsSAQdAiud68PKFQuePzwQzig/9czHCrRJae4jHMbn9wKtdMyMw
            D/VK0AvNlqVZlvoBiFuK4R5VeEjtg9+N2ajDfgZUOMhwEMPs2ITQxQePyboVfAyK
            0l4BWmCt5O24+7kMVHAhI2dDpeAIl+6VqOFlOYfg4vHjIi8FzJCQB6O+YC3+1jsk
            txievYa6+wQVWtYSEomE3zADF3tK8lIGcCyGOih+95DVzYnPHV5ZKmYgyfwofkyo
            =WBn1
            -----END PGP MESSAGE-----
          fp: FB3F2A3A200A09F4DD29A381C0946395407792FB
        - created_at: "2026-06-16T11:53:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjxsgKazaEGsSAQdAI1UJd13z7bcg34bcGDb/u/oWR46y7d6K4Rio1r3MVzww
            XoEdKP1t4U4PWKsbksjlzBXixPxp2RXeZ4J0TGzVduMfKbQIvjBBPsZ/UxFUnCDh
            0l4Bp67MXtN2JCwvWUB913IrveQw/UWw2CdO9B+7EJE4qVPch+D7wl3ThbCSVzk5
            z8STnyg2ifzmoAx2EfT/3AQXHRd7AUTGxN9GIMrFQ/bO9NauGQBFx/lseDoxhcFj
            =m/H5
            -----END PGP MESSAGE-----
          fp: 97BAD070076E18F23DE40CF367FBD7D6A827909E
    unencrypted_suffix: _unencrypted
    version: 3.9.0
