{{- if not (and .Values.tls (and .Values.tls.key .Values.tls.crt)) }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: "{{ .Values.cloudflare_api_token }}"
{{- end }}