apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
stringData:
  runner-registration-token: "" # need to leave as an empty string for compatibility reasons
  runner-token: "{{ .Values.gitlabRunnertoken }}"
