{{- if and $.Values.tls (and $.Values.tls.crt $.Values.tls.key) }}
{{- range $.Values.ingress.tls }}
{{ if .secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/tls
stringData:
  # You can include additional key value pairs as you do with Opaque Secrets
  tls.crt: {{- $.Values.tls.crt | toYaml | indent 2 }}
  tls.key: {{- $.Values.tls.key | toYaml | indent 2 }}
{{- end }}
{{- end }}
{{- end }}