apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fairagro-basic-middleware.fullname" . }}
  labels:
    {{- include "fairagro-basic-middleware.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.outputVolume.size }}
  {{- with .Values.outputVolume.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}