apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fairagro-basic-middleware.fullname" . }}
  labels:
    {{- include "fairagro-basic-middleware.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ .Values.sshPrivateKey | quote }}
